name: Test Telegram

on:
  workflow_dispatch: {}   # handmatig starten

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d '{"chat_id":"'"${{ secrets.TELEGRAM_CHAT_ID }}"'","text":"✅ Telegram werkt!","disable_web_page_preview":true}'
