name: Test Telegram

on:
  workflow_dispatch:   # handmatig starten

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Send test message
        run: |
          echo "Stuur testbericht naar Telegram"
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="✅ Hallo! Dit is een testbericht vanaf GitHub Actions."
